version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solarsim
    working_dir: /var/www/html
    expose:
      - "9000"
    networks:
      - laravel-network
    depends_on:
      - db

  nginx-config:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/http-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./:/var/www/html
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/ssl-conf:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel-network

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./:/var/www/html
    networks:
      - laravel-network

  db:
    image: postgres:16
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: laravelpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  pgdata:
