services:
  solarsim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solarsim
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
    ports:
      - "9000:9000"
      - "5173:5173"
    depends_on:
      - solarsim_postgres

  solarsim_postgres:
    image: postgres:16
    container_name: solarsim_postgres
    environment:
      POSTGRES_DB: solarsim
      POSTGRES_USER: solarsimuser
      POSTGRES_PASSWORD: solarsimpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  solarsim_nginx:
    image: nginx:latest
    container_name: solarsim_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - solarsim

volumes:
  pgdata:
