name: Deploy to Production on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS host to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to VPS
        run: |
          APP_BASE_DIR="$(echo '${{ secrets.VPS_PATH }}' | tr -d '\n' | xargs)"
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.env' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:"$APP_BASE_DIR"

      - name: Create SQLite database if not exists
        run: |
          APP_BASE_DIR="$(echo '${{ secrets.VPS_PATH }}' | tr -d '\n' | xargs)"
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            DB_DIR="\$APP_BASE_DIR/database"
            DB_FILE="\$DB_DIR/database.sqlite"

            mkdir -p "\$DB_DIR"
            echo "Ensured directory exists: \$DB_DIR"

            if [ ! -f "\$DB_FILE" ]; then
              touch "\$DB_FILE"
              echo "Created SQLite database file: \$DB_FILE"
            else
              echo "SQLite database file already exists: \$DB_FILE"
            fi
          EOF

      - name: Setup .env on VPS
        run: |
          APP_BASE_DIR="$(echo '${{ secrets.VPS_PATH }}' | tr -d '\n' | xargs)"
          DB_PATH="\$APP_BASE_DIR/database/database.sqlite"
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            printf "APP_NAME=solarsim\n" > "\$APP_BASE_DIR/.env"
            printf "APP_ENV=production\n" >> "\$APP_BASE_DIR/.env"
            printf "APP_KEY=\n" >> "\$APP_BASE_DIR/.env"
            printf "APP_DEBUG=false\n" >> "\$APP_BASE_DIR/.env"
            printf "APP_URL=https://solarsim.app.br\n" >> "\$APP_BASE_DIR/.env"
            printf "DB_CONNECTION=sqlite\n" >> "\$APP_BASE_DIR/.env"
            printf "DB_DATABASE=\$DB_PATH\n" >> "\$APP_BASE_DIR/.env"

            cd "\$APP_BASE_DIR"
            php artisan key:generate --force
            echo ".env file setup complete and app key generated."
          EOF

      - name: Install dependencies and run Laravel commands
        run: |
          APP_BASE_DIR="$(echo '${{ secrets.VPS_PATH }}' | tr -d '\n' | xargs)"
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            cd "\$APP_BASE_DIR"
            composer install --no-dev --optimize-autoloader
            echo "Composer dependencies installed."

            php artisan migrate --force
            echo "Database migrations completed."

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            echo "Laravel caches cleared and regenerated."
          EOF
