name: Deploy Laravel + Docker to VPS

on:
  push:
    branches:
      - ci/100-alterar-metodo-de-deploy-para-deploy-com-docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS host to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to VPS deploy directory
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.env' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/deploy

      - name: Setup .env on VPS from secret
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "printf '%s\n' '${{ secrets.DOTENV_CONTENT }}' > /home/${{ secrets.VPS_USER }}/deploy/.env"

      - name: Build and start app, db, nginx Docker containers on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose build app db nginx &&
            docker compose up -d app db nginx
          "
      
      - name: Run Certbot to obtain certificates
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose run --rm certbot certonly --webroot --webroot-path=/var/www/html --email brunohdwinter@gmail.com --agree-tos --no-eff-email --force-renewal -d solarsim.app.br
          "
      
      - name: Reload nginx to apply SSL certificates
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose restart nginx
          "

      - name: Run Laravel artisan commands inside container
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose exec app php artisan migrate --force &&
            docker compose exec app php artisan config:cache &&
            docker compose exec app php artisan route:cache &&
            docker compose exec app php artisan view:cache
          "

      - name: Build front-end assets inside container
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose exec app npm install &&
            docker compose exec app npm run build
          "
