name: Deploy Laravel + Docker to VPS

on:
  push:
    branches:
      - ci/100-alterar-metodo-de-deploy-para-deploy-com-docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS host to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to VPS deploy directory
        run: |
          rsync -avz --delete --progress \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='vendor' \
          --exclude='.env' \
          --exclude='public/build' \
          --exclude='docker/certs/letsencrypt' \
          ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/deploy

      - name: Setup .env on VPS from secret
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo -e \"${{ secrets.DOTENV_CONTENT }}\" > /home/${{ secrets.VPS_USER }}/deploy/.env"

      - name: Build and start app Docker containers on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose build app &&
            docker compose up -d app
          "

      - name: Run Laravel artisan commands inside container
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose exec app sh -c '
              composer install &&
              php artisan key:generate &&
              php artisan migrate --force &&
              php artisan config:cache &&
              php artisan route:cache &&
              php artisan view:cache
            '
          "

      - name: Build front-end assets inside container
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/deploy &&
            docker compose exec app sh -c '
              npm install &&
              npm run build
            '
          "
