name: Deploy Laravel + Docker to VPS

on:
  push:
    branches:
      - ci/100-alterar-metodo-de-deploy-para-deploy-com-docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to VPS home directory
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.env' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}

      - name: Setup .env on VPS from secret
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo '${{ secrets.DOTENV_CONTENT }}' > /home/${{ secrets.VPS_USER }}/.env"

      - name: Build and start Docker containers on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }} &&
            docker-compose build &&
            docker-compose up -d
          "

      - name: Run Laravel artisan commands inside container
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }} &&
            docker-compose exec app php artisan migrate --force &&
            docker-compose exec app php artisan config:cache &&
            docker-compose exec app php artisan route:cache &&
            docker-compose exec app php artisan view:cache
          "

      - name: Build front-end assets inside container
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }} &&
            docker-compose exec app npm install &&
            docker-compose exec app npm run build
          "
