name: Test SSH Connection

on:
  push:
    branches:
      - ci/127-ci-mudar-deploy-para-novo-servidor

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Debug SSH connection
        run: ssh -v -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} exit
