name: Test SSH Connection

on:
  push:
    branches:
      - ci/127-ci-mudar-deploy-para-novo-servidor

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Sync files to VPS deploy directory
        run: |
          rsync -e "ssh -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no" -avz --delete --progress \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.env' \
            --exclude='public/build' \
            --exclude='docker/certs/letsencrypt' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/deploy