name: Test SSH Connection

on:
  push:
    branches:
      - ci/127-ci-mudar-deploy-para-novo-servidor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Connect to VPS and print Hello World
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -p ${{ secrets.VPS_PORT }} \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
              "echo 'Hello World from GitHub Actions using variables!' >> /tmp/hello_from_github.txt && cat /tmp/hello_from_github.txt"